replicaCount: 2

image:
  repository: 980377181750.dkr.ecr.eu-west-3.amazonaws.com/front
  tag: 15
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70